In [1]:
class A:
    def __init__(self,):
        self.x = {
            'x': 10
        }

    def todo(self):
        temp = self.x 
        temp['x'] = 20

obj = A()
print(obj.x)
obj.todo()
print(obj.x)


{'x': 10}
{'x': 20}


In [2]:
while True:
    print("yo")
    if 1: 
        break

    for a in range(10):
        print(a)

yo


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import random
from typing import Tuple, List, Optional, Dict

In [7]:
class SnakeModel(nn.Module):
    """
    the output is interpreted as follows
    right, left, up, down
    """

    def __init__(self,
                 input_units=4,
                 hidden_units=2,
                 output_units=1):
        super().__init__()
        self.l = nn.Sequential(
            nn.Linear(input_units, hidden_units),
            nn.ELU(),
            nn.Linear(hidden_units, output_units),
            nn.Softmax(dim=-1),
        )

    def forward(self, state: torch.Tensor) -> torch.Tensor:
        x = self.l(state)
        return x

In [29]:
m1 = SnakeModel()
m2 = SnakeModel()

In [48]:
m1.state_dict()

OrderedDict([('l.0.weight',
              tensor([[ 0.1573,  0.3781,  0.4966, -0.0021],
                      [ 0.3545, -0.0965, -0.4449,  0.2109]])),
             ('l.0.bias', tensor([-0.1724,  0.0932])),
             ('l.2.weight', tensor([[-0.5984, -0.1193]])),
             ('l.2.bias', tensor([-0.6479]))])

In [38]:
for n, a in m1.named_parameters():
    if "weight" in n:
        print(n)
        print(a)
        print()

l.0.weight
Parameter containing:
tensor([[ 0.1573,  0.3781,  0.4966, -0.0021],
        [ 0.3545, -0.0965, -0.4449,  0.2109]], requires_grad=True)

l.2.weight
Parameter containing:
tensor([[-0.5984, -0.1193]], requires_grad=True)



In [137]:
new_m = SnakeModel()
for n, a in new_m.named_parameters():
    print(n, a)

l.0.weight Parameter containing:
tensor([[ 0.2062,  0.2232,  0.2643,  0.0694],
        [-0.1394,  0.2161, -0.2874,  0.1666]], requires_grad=True)
l.0.bias Parameter containing:
tensor([-0.0912,  0.0815], requires_grad=True)
l.2.weight Parameter containing:
tensor([[0.2655, 0.4711]], requires_grad=True)
l.2.bias Parameter containing:
tensor([0.1355], requires_grad=True)


In [138]:
# with torch.no_grad():
for (n1, a1), (n2, a2), (n3, a3) in zip(m1.named_parameters(), m2.named_parameters(), new_m.named_parameters()):
    with torch.no_grad():
        if "weight" in n3:
            a3.copy_(a1 * 0.5 + a2 * 0.5)

In [139]:
# new_m = SnakeModel()
for n, a in new_m.named_parameters():
    print(n, a)

l.0.weight Parameter containing:
tensor([[ 0.0206,  0.0442,  0.0253, -0.1082],
        [-0.0612, -0.0072,  0.0104, -0.0377]], requires_grad=True)
l.0.bias Parameter containing:
tensor([-0.0912,  0.0815], requires_grad=True)
l.2.weight Parameter containing:
tensor([[-0.0433,  0.3306]], requires_grad=True)
l.2.bias Parameter containing:
tensor([0.1355], requires_grad=True)


In [108]:
new_m = SnakeModel()
for n, a in new_m.named_parameters():
    print(n, a)

l.0.weight Parameter containing:
tensor([[-0.3125,  0.4888, -0.1942, -0.1477],
        [ 0.4173, -0.2080, -0.2899, -0.0647]], requires_grad=True)
l.0.bias Parameter containing:
tensor([-0.0384, -0.1317], requires_grad=True)
l.2.weight Parameter containing:
tensor([[0.2259, 0.2261]], requires_grad=True)
l.2.bias Parameter containing:
tensor([0.4160], requires_grad=True)


In [22]:
2 // 2

1

In [28]:
a = 1000
while a != 0:
    print(a)
    top = a // 2
    if top <= 1:
        break

    if top % 2 != 0:
        top -= 1
    a = top 

1000
500
250
124
62
30
14
6
2


In [94]:
d = dict()
d[0] = {
    'a': 10,
}
d[1] = {
    'a': 100
}

new_dict = dict(sorted(d.items(), key = lambda item: -item[1]['a']))
print(d), print(new_dict), 
type(new_dict)

{0: {'a': 10}, 1: {'a': 100}}
{1: {'a': 100}, 0: {'a': 10}}


dict

In [141]:
for a in range(0, 4, 2):
    print(a)

0
2
